apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: orchestrator
data:
  GIT_SYNC_USERNAME: dmluaWNpdXNnYWx2YW9pYQ==
  GITSYNC_USERNAME: dmluaWNpdXNnYWx2YW9pYQ==
  GIT_SYNC_PASSWORD: Z2hwX0E0ckdzcDIwRnBtOWFKbURPczFVWUg4VnZDb3hmcDNkUmMyUg==
  GITSYNC_PASSWORD: Z2hwX0E0ckdzcDIwRnBtOWFKbURPczFVWUg4VnZDb3hmcDNkUmMyUg==
